project_id = "nfnodtneknrumxpfftbr"

[functions.classify-invoice]
verify_jwt = false

[functions.parse-account-book]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false